export const subjects = [
  "maths",
  "language",
  "science",
  "history",
  "coding",
  "economics",
];

export const subjectsColors = {
  science: "#E5D0FF",
  maths: "#FFDA6E",
  language: "#BDE7FF",
  coding: "#FFC8E4",
  history: "#FFECC8",
  economics: "#C8FFDF",
};

export const voices = {
  male: { casual: "2BJW5coyhAzSr8STdHbE", formal: "c6SfcYrb2t09NHXiT80T" },
  female: { casual: "ZIlrSGI4jZqobxRKprJz", formal: "sarah" },
};

export const recentSessions = [
  {
    id: "1",
    subject: "science",
    name: "Neura the Brainy Explorer",
    topic: "Neural Network of the Brain",
    duration: 45,
    color: "#E5D0FF",
  },
  {
    id: "2",
    subject: "maths",
    name: "Countsy the Number Wizard",
    topic: "Derivatives & Integrals",
    duration: 30,
    color: "#FFDA6E",
  },
  {
    id: "3",
    subject: "language",
    name: "Verba the Vocabulary Builder",
    topic: "English Literature",
    duration: 30,
    color: "#BDE7FF",
  },
  {
    id: "4",
    subject: "coding",
    name: "Codey the Logic Hacker",
    topic: "Intro to If-Else Statements",
    duration: 45,
    color: "#FFC8E4",
  },
  {
    id: "5",
    subject: "history",
    name: "Memo, the Memory Keeper",
    topic: "World Wars: Causes & Consequences",
    duration: 15,
    color: "#FFECC8",
  },
  {
    id: "6",
    subject: "economics",
    name: "The Market Maestro",
    topic: "The Basics of Supply & Demand",
    duration: 10,
    color: "#C8FFDF",
  },
];

export const cards = [
  {
    name: "The Charriot",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheCharriot.jpg",
    seed: "",
    meaning: "The Charriot represents determination, willpower, and control. It signifies overcoming obstacles and achieving victory through discipline and focus.",
    reversedMeaning: "When reversed, The Charriot can indicate a lack of direction, loss of control, or feeling overwhelmed. It suggests the need to regain focus and determination to overcome challenges.",
  },
  {
    name: "The Death",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheDeath.jpg",
    seed: "",
    meaning: "The Death card symbolizes transformation, endings, and new beginnings. It signifies the end of a cycle and the start of something new, often leading to personal growth and renewal.",
    reversedMeaning: "When reversed, The Death card can indicate resistance to change, fear of the unknown, or stagnation. It suggests the need to embrace transformation and let go of what no longer serves you.",
  },
  {
    name: "The Devil",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheDevil.jpg",
    seed: "",
    meaning: "The Devil card represents temptation, addiction, and materialism. It signifies being trapped by desires or unhealthy attachments, urging you to confront your inner demons and regain control.",
    reversedMeaning: "When reversed, The Devil can indicate breaking free from bondage, overcoming addiction, or releasing negative patterns. It suggests a newfound sense of freedom and empowerment.",
  },
  {
    name: "The Emperor",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheEmperor.jpg",
    seed: "",
    meaning: "The Emperor symbolizes authority, structure, and stability. It signifies leadership, control, and the establishment of order in your life. It encourages you to take charge and assert your power.",
    reversedMeaning: "When reversed, The Emperor can indicate abuse of power, rigidity, or lack of control. It suggests the need to reassess your authority and find a balance between structure and flexibility.",
  },
  {
    name: "The Empress",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheEmpress.jpg",
    seed: "",
    meaning: "The Empress represents fertility, abundance, and nurturing. It signifies creativity, motherhood, and the beauty of nature. It encourages you to embrace your feminine energy and connect with your intuition.",
    reversedMeaning: "When reversed, The Empress can indicate neglect, lack of self-care, or creative blocks. It suggests the need to nurture yourself and find balance in your life.",
  },
  {
    name: "The Fool",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheFool.jpg",
    seed: "",
    meaning: "The Fool represents new beginnings, spontaneity, and taking risks. It signifies a fresh start, embracing the unknown, and trusting your instincts. It encourages you to step out of your comfort zone.",
    reversedMeaning: "When reversed, The Fool can indicate recklessness, naivety, or fear of change. It suggests the need to be cautious and consider the consequences of your actions before taking a leap of faith.",
  },
  {
    name: "The Hanged Man",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheHangedMan.jpg",
    seed: "",
    meaning: "The Hanged Man";
    reversedMeaning: "When reversed, The"
  },
  {
    name: "The Hermit",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheHermit.jpg",
    seed: "",
    meaning: "The Hermit represents introspection, solitude, and inner guidance. It signifies a time for self-reflection, seeking wisdom within, and finding clarity in your path. It encourages you to embrace solitude for personal growth.",
    reversedMeaning: "When reversed, The Hermit can indicate isolation, loneliness, or avoidance of self-reflection. It suggests the need to reconnect with others and seek guidance from trusted sources.",
  },
  {
    name: "The Hierophant",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheHierophant.jpg",
    seed: "",
    meaning: "The Hierophant symbolizes tradition, spirituality, and conformity. It signifies seeking guidance from established institutions or mentors. It encourages you to explore your spiritual beliefs and connect with your higher self.",
    reversedMeaning: "When reversed, The Hierophant can indicate rebellion against tradition, questioning authority, or feeling disconnected from spiritual beliefs. It suggests the need to forge your own path and seek personal truth.",
  },
  {
    name: "The HIgh Priestess",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheHighPriestess.jpg",
    seed: "",
    meaning: "The High Priestess represents intuition, mystery, and inner wisdom. It signifies a deep connection to your subconscious mind and the need to trust your instincts. It encourages you to explore your spiritual side and embrace the unknown.",
    reversedMeaning: "When reversed, The High Priestess can indicate confusion, lack of intuition, or ignoring your inner voice. It suggests the need to reconnect with your intuition and trust your instincts.",
  },
  {
    name: "The Judgement",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheJudgement.jpg",
    seed: "",
    meaning: "The Judgement card symbolizes rebirth, renewal, and self-reflection. It signifies a time for evaluation, making important decisions, and embracing personal transformation. It encourages you to let go of the past and embrace new opportunities.",
    reversedMeaning: "When reversed, The Judgement can indicate self-doubt, fear of change, or avoiding necessary decisions. It suggests the need to confront your past and take responsibility for your actions to move forward.",
  },
  {
    name: "The Justice",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheJustice.jpg",
    seed: "",
    meaning: "The Justice card represents fairness, balance, and truth. It signifies the need for honesty, integrity, and making just decisions. It encourages you to seek fairness in your actions and relationships.",
    reversedMeaning: "When reversed, The Justice can indicate dishonesty, unfairness, or lack of accountability. It suggests the need to reassess your actions and ensure that you are acting with integrity and fairness.",
  },
  {
    name: "The Lovers",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheLovers.jpg",
    seed: "",
    meaning: "The Lovers card represents love, harmony, and deep connections. It signifies romantic relationships, partnerships, and choices that align with your values. It encourages you to embrace love and make decisions that resonate with your heart.",
    reversedMeaning: "When reversed, The Lovers can indicate disharmony, imbalance, or difficult choices in relationships. It suggests the need to reassess your connections and make decisions that align with your true self.",
  },
  {
    name: "The Magician",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheMagician.jpg",
    seed: "",
    meaning: "The Magician symbolizes manifestation, creativity, and resourcefulness. It signifies the power to turn ideas into reality and take action towards your goals. It encourages you to harness your skills and talents to create the life you desire.",
    reversedMeaning: "When reversed, The Magician can indicate manipulation, lack of focus, or misuse of power. It suggests the need to reassess your intentions and ensure that you are using your abilities for positive outcomes.",
  },
  {
    name: "The Moon",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheMoon.jpg",
    seed: "",
    meaning: "The Moon represents intuition, dreams, and the subconscious mind. It signifies the need to trust your instincts, explore your emotions, and navigate through uncertainty. It encourages you to embrace your inner world and seek clarity in the midst of confusion.",
    reversedMeaning: "When reversed, The Moon can indicate fear, anxiety, or illusions. It suggests the need to confront your fears, seek clarity, and trust your intuition to navigate through challenging situations.",
  },
  {
    name: "The Star",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheStar.jpg",
    seed: "",
    meaning: "The Star symbolizes hope, inspiration, and renewal. It signifies a sense of optimism, healing, and finding your true purpose. It encourages you to embrace your dreams and trust in the universe's guidance.",
    reversedMeaning: "When reversed, The Star can indicate despair, lack of faith, or feeling lost. It suggests the need to reconnect with your inner light, find hope, and trust in the possibilities that lie ahead.",
  },
  {
    name: "The Strength",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheStrength.jpg",
    seed: "",
    meaning: "The Strength card represents courage, inner strength, and resilience. It signifies the ability to overcome challenges, face fears, and tap into your inner power. It encourages you to embrace your strengths and approach situations with confidence.",
    reversedMeaning: "When reversed, The Strength can indicate self-doubt, weakness, or lack of confidence. It suggests the need to reconnect with your inner strength and find the courage to face challenges head-on.",
  },
  {
    name: "The Sun",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheSun.jpg",
    seed: "",
    meaning: "The Sun symbolizes joy, success, and positivity. It signifies a time of happiness, abundance, and clarity. It encourages you to embrace your inner light and celebrate your achievements.",
    reversedMeaning: "When reversed, The Sun can indicate temporary setbacks, lack of clarity, or feeling down. It suggests the need to find joy in the little things and regain a positive outlook on life.",
  },
  {
    name: "The Temperance",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheTemperance.jpg",
    seed: "",
    meaning: "The Temperance card represents balance, harmony, and moderation. It signifies the need to find equilibrium in your life, integrate different aspects, and practice patience. It encourages you to seek a middle ground and avoid extremes.",
    reversedMeaning: "When reversed, The Temperance can indicate imbalance, excess, or lack of moderation. It suggests the need to reassess your priorities and find a healthier balance in your life.",
  },
  {
    name: "The Tower",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheTower.jpg",
    seed: "",
    meaning: "The Tower symbolizes sudden change, upheaval, and revelation. It signifies a breaking down of old structures, leading to transformation and new perspectives. It encourages you to embrace change and learn from unexpected events.",
    reversedMeaning: "When reversed, The Tower can indicate avoidance of change, fear of upheaval, or resisting necessary transformations. It suggests the need to confront challenges and embrace the lessons that come with them.",
  },
  {
    name: "The Wheel of Fortune",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheWheelOfFortune.jpg",
    seed: "",
    meaning: "The Wheel of Fortune represents cycles, destiny, and change. It signifies the ebb and flow of life, reminding you that everything is temporary. It encourages you to embrace the ups and downs and trust in the natural order of things.",
    reversedMeaning: "When reversed, The Wheel of Fortune can indicate resistance to change, feeling stuck, or being at the mercy of external circumstances. It suggests the need to adapt to the changing tides and find your own path amidst uncertainty.",
  },
  {
    name: "The World",
    arcana: "Major",
    image: "/images/Tatots/MajorArcana/TheWorld.jpg",
    seed: "",
    meaning: "The World symbolizes completion, fulfillment, and achievement. It signifies the successful conclusion of a journey, reaching your goals, and finding a sense of wholeness. It encourages you to celebrate your accomplishments and embrace new beginnings.",
    reversedMeaning: "When reversed, The World can indicate unfinished business, lack of closure, or feeling incomplete. It suggests the need to reflect on your journey, tie up loose ends, and prepare for new adventures.",
  },

];