export const subjects = [
  "maths",
  "language",
  "science",
  "history",
  "coding",
  "economics",
];

export const subjectsColors = {
  science: "#E5D0FF",
  maths: "#FFDA6E",
  language: "#BDE7FF",
  coding: "#FFC8E4",
  history: "#FFECC8",
  economics: "#C8FFDF",
};

export const voices = {
  male: { casual: "2BJW5coyhAzSr8STdHbE", formal: "c6SfcYrb2t09NHXiT80T" },
  female: { casual: "ZIlrSGI4jZqobxRKprJz", formal: "sarah" },
};

export const deck = [
  {
    name: "The Charriot",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheCharriot.jpg",
    seed: "",
    meaning: "The Charriot represents determination, willpower, and control. It signifies overcoming obstacles and achieving victory through discipline and focus.",
    reversedMeaning: "When reversed, The Charriot can indicate a lack of direction, loss of control, or feeling overwhelmed. It suggests the need to regain focus and determination to overcome challenges.",
  },
  {
    name: "The Death",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheDeath.jpg",
    seed: "",
    meaning: "The Death card symbolizes transformation, endings, and new beginnings. It signifies the end of a cycle and the start of something new, often leading to personal growth and renewal.",
    reversedMeaning: "When reversed, The Death card can indicate resistance to change, fear of the unknown, or stagnation. It suggests the need to embrace transformation and let go of what no longer serves you.",
  },
  {
    name: "The Devil",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheDevil.jpg",
    seed: "",
    meaning: "The Devil card represents temptation, addiction, and materialism. It signifies being trapped by desires or unhealthy attachments, urging you to confront your inner demons and regain control.",
    reversedMeaning: "When reversed, The Devil can indicate breaking free from bondage, overcoming addiction, or releasing negative patterns. It suggests a newfound sense of freedom and empowerment.",
  },
  {
    name: "The Emperor",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheEmperor.jpg",
    seed: "",
    meaning: "The Emperor symbolizes authority, structure, and stability. It signifies leadership, control, and the establishment of order in your life. It encourages you to take charge and assert your power.",
    reversedMeaning: "When reversed, The Emperor can indicate abuse of power, rigidity, or lack of control. It suggests the need to reassess your authority and find a balance between structure and flexibility.",
  },
  {
    name: "The Empress",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheEmpress.jpg",
    seed: "",
    meaning: "The Empress represents fertility, abundance, and nurturing. It signifies creativity, motherhood, and the beauty of nature. It encourages you to embrace your feminine energy and connect with your intuition.",
    reversedMeaning: "When reversed, The Empress can indicate neglect, lack of self-care, or creative blocks. It suggests the need to nurture yourself and find balance in your life.",
  },
  {
    name: "The Fool",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheFool.jpg",
    seed: "",
    meaning: "The Fool represents new beginnings, spontaneity, and taking risks. It signifies a fresh start, embracing the unknown, and trusting your instincts. It encourages you to step out of your comfort zone.",
    reversedMeaning: "When reversed, The Fool can indicate recklessness, naivety, or fear of change. It suggests the need to be cautious and consider the consequences of your actions before taking a leap of faith.",
  },
  {
    name: "The Hanged Man",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheHangedMan.png",
    seed: "",
    meaning: "The Hanged Man represents surrender, letting go, and seeing things from a different perspective. It signifies a pause in action, encouraging you to reflect and gain new insights before moving forward. It encourages you to embrace patience and trust the process.",
    reversedMeaning: "WHen reversed, The Hanged Man can indicate stagnation, feeling stuck, or resistance to change. It suggests the need to release control and allow things to unfold naturally.",
  },
  {
    name: "The Hermit",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheHermit.jpg",
    seed: "",
    meaning: "The Hermit represents introspection, solitude, and inner guidance. It signifies a time for self-reflection, seeking wisdom within, and finding clarity in your path. It encourages you to embrace solitude for personal growth.",
    reversedMeaning: "When reversed, The Hermit can indicate isolation, loneliness, or avoidance of self-reflection. It suggests the need to reconnect with others and seek guidance from trusted sources.",
  },
  {
    name: "The Hierophant",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheHierophant.jpg",
    seed: "",
    meaning: "The Hierophant symbolizes tradition, spirituality, and conformity. It signifies seeking guidance from established institutions or mentors. It encourages you to explore your spiritual beliefs and connect with your higher self.",
    reversedMeaning: "When reversed, The Hierophant can indicate rebellion against tradition, questioning authority, or feeling disconnected from spiritual beliefs. It suggests the need to forge your own path and seek personal truth.",
  },
  {
    name: "The HIgh Priestess",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheHighPriestess.jpg",
    seed: "",
    meaning: "The High Priestess represents intuition, mystery, and inner wisdom. It signifies a deep connection to your subconscious mind and the need to trust your instincts. It encourages you to explore your spiritual side and embrace the unknown.",
    reversedMeaning: "When reversed, The High Priestess can indicate confusion, lack of intuition, or ignoring your inner voice. It suggests the need to reconnect with your intuition and trust your instincts.",
  },
  {
    name: "The Judgment",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheJudgment.jpg",
    seed: "",
    meaning: "The Judgment card symbolizes rebirth, renewal, and self-reflection. It signifies a time for evaluation, making important decisions, and embracing personal transformation. It encourages you to let go of the past and embrace new opportunities.",
    reversedMeaning: "When reversed, The Judgemnt can indicate self-doubt, fear of change, or avoiding necessary decisions. It suggests the need to confront your past and take responsibility for your actions to move forward.",
  },
  {
    name: "The Justice",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheJustice.jpg",
    seed: "",
    meaning: "The Justice card represents fairness, balance, and truth. It signifies the need for honesty, integrity, and making just decisions. It encourages you to seek fairness in your actions and relationships.",
    reversedMeaning: "When reversed, The Justice can indicate dishonesty, unfairness, or lack of accountability. It suggests the need to reassess your actions and ensure that you are acting with integrity and fairness.",
  },
  {
    name: "The Lovers",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheLovers.jpg",
    seed: "",
    meaning: "The Lovers card represents love, harmony, and deep connections. It signifies romantic relationships, partnerships, and choices that align with your values. It encourages you to embrace love and make decisions that resonate with your heart.",
    reversedMeaning: "When reversed, The Lovers can indicate disharmony, imbalance, or difficult choices in relationships. It suggests the need to reassess your connections and make decisions that align with your true self.",
  },
  {
    name: "The Magician",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheMagician.jpg",
    seed: "",
    meaning: "The Magician symbolizes manifestation, creativity, and resourcefulness. It signifies the power to turn ideas into reality and take action towards your goals. It encourages you to harness your skills and talents to create the life you desire.",
    reversedMeaning: "When reversed, The Magician can indicate manipulation, lack of focus, or misuse of power. It suggests the need to reassess your intentions and ensure that you are using your abilities for positive outcomes.",
  },
  {
    name: "The Moon",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheMoon.jpg",
    seed: "",
    meaning: "The Moon represents intuition, dreams, and the subconscious mind. It signifies the need to trust your instincts, explore your emotions, and navigate through uncertainty. It encourages you to embrace your inner world and seek clarity in the midst of confusion.",
    reversedMeaning: "When reversed, The Moon can indicate fear, anxiety, or illusions. It suggests the need to confront your fears, seek clarity, and trust your intuition to navigate through challenging situations.",
  },
  {
    name: "The Star",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheStar.jpg",
    seed: "",
    meaning: "The Star symbolizes hope, inspiration, and renewal. It signifies a sense of optimism, healing, and finding your true purpose. It encourages you to embrace your dreams and trust in the universe's guidance.",
    reversedMeaning: "When reversed, The Star can indicate despair, lack of faith, or feeling lost. It suggests the need to reconnect with your inner light, find hope, and trust in the possibilities that lie ahead.",
  },
  {
    name: "The Strength",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheStrength.jpg",
    seed: "",
    meaning: "The Strength card represents courage, inner strength, and resilience. It signifies the ability to overcome challenges, face fears, and tap into your inner power. It encourages you to embrace your strengths and approach situations with confidence.",
    reversedMeaning: "When reversed, The Strength can indicate self-doubt, weakness, or lack of confidence. It suggests the need to reconnect with your inner strength and find the courage to face challenges head-on.",
  },
  {
    name: "The Sun",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheSun.jpg",
    seed: "",
    meaning: "The Sun symbolizes joy, success, and positivity. It signifies a time of happiness, abundance, and clarity. It encourages you to embrace your inner light and celebrate your achievements.",
    reversedMeaning: "When reversed, The Sun can indicate temporary setbacks, lack of clarity, or feeling down. It suggests the need to find joy in the little things and regain a positive outlook on life.",
  },
  {
    name: "The Temperance",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheTemperance.jpg",
    seed: "",
    meaning: "The Temperance card represents balance, harmony, and moderation. It signifies the need to find equilibrium in your life, integrate different aspects, and practice patience. It encourages you to seek a middle ground and avoid extremes.",
    reversedMeaning: "When reversed, The Temperance can indicate imbalance, excess, or lack of moderation. It suggests the need to reassess your priorities and find a healthier balance in your life.",
  },
  {
    name: "The Tower",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheTower.jpg",
    seed: "",
    meaning: "The Tower symbolizes sudden change, upheaval, and revelation. It signifies a breaking down of old structures, leading to transformation and new perspectives. It encourages you to embrace change and learn from unexpected events.",
    reversedMeaning: "When reversed, The Tower can indicate avoidance of change, fear of upheaval, or resisting necessary transformations. It suggests the need to confront challenges and embrace the lessons that come with them.",
  },
  {
    name: "The Wheel of Fortune",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheWheelOfFortune.jpg",
    seed: "",
    meaning: "The Wheel of Fortune represents cycles, destiny, and change. It signifies the ebb and flow of life, reminding you that everything is temporary. It encourages you to embrace the ups and downs and trust in the natural order of things.",
    reversedMeaning: "When reversed, The Wheel of Fortune can indicate resistance to change, feeling stuck, or being at the mercy of external circumstances. It suggests the need to adapt to the changing tides and find your own path amidst uncertainty.",
  },
  {
    name: "The World",
    arcana: "Major",
    image: "/images/Tarots/MajorArcana/TheWorld.jpg",
    seed: "",
    meaning: "The World symbolizes completion, fulfillment, and achievement. It signifies the successful conclusion of a journey, reaching your goals, and finding a sense of wholeness. It encourages you to celebrate your accomplishments and embrace new beginnings.",
    reversedMeaning: "When reversed, The World can indicate unfinished business, lack of closure, or feeling incomplete. It suggests the need to reflect on your journey, tie up loose ends, and prepare for new adventures.",
  },
  {
    name: "Ace of Cups",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Cups/AceOfCups.jpg",
    seed: "Cups",
    meaning: "The Ace of Cups represents new beginnings in love, emotions, and relationships. It signifies the start of a deep emotional connection, creativity, and spiritual growth. It encourages you to open your heart and embrace new experiences.",
    reversedMeaning: "When reversed, the Ace of Cups can indicate emotional blockages, unfulfilled desires, or difficulty expressing feelings. It suggests the need to heal emotional wounds and reconnect with your inner self.",
  },
  {
    name: "Two of Cups",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Cups/TwoOfCups.jpg",
    seed: "Cups",
    meaning: "The Two of Cups symbolizes partnership, harmony, and mutual respect. It signifies a deep emotional bond, collaboration, and shared values. It encourages you to nurture relationships and find balance in your connections.",
    reversedMeaning: "When reversed, the Two of Cups can indicate disharmony, imbalance, or conflicts in relationships. It suggests the need to address misunderstandings and find common ground to restore harmony.",
  },
  {
    name: "Three of Cups",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Cups/ThreeOfCups.jpg",
    seed: "Cups",
    meaning: "The Three of Cups represents celebration, friendship, and community. It signifies joyful gatherings, shared experiences, and emotional support. It encourages you to cherish your relationships and celebrate life's blessings.",
    reversedMeaning: "When reversed, the Three of Cups can indicate isolation, lack of social connections, or overindulgence. It suggests the need to reconnect with friends and find balance in your social life.",
  },
  {
    name: "Four of Cups",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Cups/FourOfCups.jpg",
    seed: "Cups",
    meaning: "The Four of Cups symbolizes contemplation, introspection, and reevaluation. It signifies a period of reflection, where you may feel disconnected or dissatisfied with your current situation. It encourages you to seek inner clarity and explore new opportunities.",
    reversedMeaning: "When reversed, the Four of Cups can indicate renewed interest, new perspectives, or a willingness to embrace change. It suggests the need to break free from stagnation and open yourself to new possibilities.",
  },
  {
    name: "Five of Cups",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Cups/FiveOfCups.jpg",
    seed: "Cups",
    meaning: "The Five of Cups represents loss, grief, and disappointment. It signifies focusing on what has been lost rather than appreciating what remains. It encourages you to acknowledge your emotions and find healing in the midst of sorrow.",
    reversedMeaning: "When reversed, the Five of Cups can indicate acceptance, moving on, or finding hope after a difficult period. It suggests the need to let go of past disappointments and embrace new opportunities for growth.",
  },
  {
    name: "Six of Cups",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Cups/SixOfCups.jpg",
    seed: "Cups",
    meaning: "The Six of Cups symbolizes nostalgia, childhood memories, and innocence. It signifies a return to simpler times, reconnecting with your inner child, and finding joy in the past. It encourages you to embrace the lessons learned from your experiences.",
    reversedMeaning: "When reversed, the Six of Cups can indicate clinging to the past, unrealistic expectations, or difficulty moving forward. It suggests the need to let go of nostalgia and focus on the present moment.",
  },
  {
    name: "Seven of Cups",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Cups/SevenOfCups.jpg",
    seed: "Cups",
    meaning: "The Seven of Cups represents choices, illusions, and daydreams. It signifies a multitude of options, but also the potential for confusion or unrealistic expectations. It encourages you to evaluate your desires and make conscious choices.",
    reversedMeaning: "When reversed, the Seven of Cups can indicate clarity, focus, or making decisions based on reality. It suggests the need to ground your dreams and take practical steps towards your goals.",
  },
  {
    name: "Eight of Cups",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Cups/EightOfCups.jpg",
    seed: "Cups",
    meaning: "The Eight of Cups symbolizes walking away, seeking deeper meaning, and emotional detachment. It signifies a desire for personal growth, leaving behind what no longer serves you, and embarking on a new journey. It encourages you to trust your intuition and follow your heart.",
    reversedMeaning: "When reversed, the Eight of Cups can indicate avoidance, fear of change, or staying in a situation that no longer fulfills you. It suggests the need to confront your emotions and make choices that align with your true self.",
  },
  {
    name: "Nine of Cups",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Cups/NineOfCups.jpg",
    seed: "Cups",
    meaning: "The Nine of Cups represents emotional fulfillment, contentment, and wishes coming true. It signifies a sense of satisfaction, joy, and gratitude for what you have achieved. It encourages you to celebrate your accomplishments and appreciate the blessings in your life.",
    reversedMeaning: "When reversed, the Nine of Cups can indicate dissatisfaction, unfulfilled desires, or overindulgence. It suggests the need to reassess your goals and find true happiness within yourself rather than relying on external sources.",
  },
  {
    name: "Ten of Cups",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Cups/TenOfCups.jpg",
    seed: "Cups",
    meaning: "The Ten of Cups symbolizes emotional harmony, family, and lasting happiness. It signifies a sense of fulfillment in relationships, deep connections, and shared joy. It encourages you to nurture your loved ones and create a supportive environment.",
    reversedMeaning: "When reversed, the Ten of Cups can indicate disharmony, conflicts within relationships, or unmet expectations. It suggests the need to address underlying issues and work towards restoring harmony and understanding.",
  },
  {
    name: "Page of Cups",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Cups/PageOfCups.jpg",
    seed: "Cups",
    meaning: "The Page of Cups represents creativity, intuition, and emotional exploration. It signifies a youthful spirit, new ideas, and the potential for emotional growth. It encourages you to embrace your imagination and express your feelings openly.",
    reversedMeaning: "When reversed, the Page of Cups can indicate emotional immaturity, unrealistic expectations, or difficulty expressing feelings. It suggests the need to develop emotional intelligence and find healthy outlets for your creativity.",
  },
  {
    name: "Knight of Cups",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Cups/KnightOfCups.jpg",
    seed: "Cups",
    meaning: "The Knight of Cups symbolizes romance, charm, and idealism. It signifies a quest for love, emotional depth, and pursuing your dreams with passion. It encourages you to follow your heart and embrace the beauty of life.",
    reversedMeaning: "When reversed, the Knight of Cups can indicate unrealistic expectations, emotional instability, or being overly idealistic. It suggests the need to ground your emotions and find a balance between dreams and reality.",
  },
  {
    name: "Queen of Cups",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Cups/QueenOfCups.jpg",
    seed: "Cups",
    meaning: "The Queen of Cups represents compassion, intuition, and emotional intelligence. It signifies a nurturing and empathetic nature, encouraging you to trust your instincts and connect with your emotions. It encourages you to create a supportive environment for yourself and others.",
    reversedMeaning: "When reversed, the Queen of Cups can indicate emotional overwhelm, lack of boundaries, or difficulty expressing feelings. It suggests the need to prioritize self-care and find balance in your emotional life.",
  },
  {
    name: "King of Cups",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Cups/KingOfCups.jpg",
    seed: "Cups",
    meaning: "The King of Cups symbolizes emotional maturity, wisdom, and diplomacy. It signifies a balanced approach to emotions, using intuition and compassion to navigate challenges. It encourages you to lead with empathy and create harmony in your relationships.",
    reversedMeaning: "When reversed, the King of Cups can indicate emotional detachment, manipulation, or difficulty expressing feelings. It suggests the need to reconnect with your emotions and find healthy ways to communicate and connect with others.",
  },
  {
    name: "Ace of Pentacles",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Pentacles/AceOfPentacles.jpg",
    seed: "Pentacles",
    meaning: "The Ace of Pentacles represents new beginnings in material and financial matters. It signifies opportunities for growth, prosperity, and stability. It encourages you to take practical steps towards your goals and embrace abundance.",
    reversedMeaning: "When reversed, the Ace of Pentacles can indicate missed opportunities, financial setbacks, or lack of practicality. It suggests the need to reassess your financial situation and make conscious choices to create stability.",
  },
  {
    name: "Two of Pentacles",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Pentacles/TwoOfPentacles.jpg",
    seed: "Pentacles",
    meaning: "The Two of Pentacles symbolizes balance, adaptability, and juggling multiple responsibilities. It signifies the need to find harmony in your life, manage your time effectively, and embrace change. It encourages you to stay flexible and prioritize your commitments.",
  reversedMeaning: "When reversed, the Two of Pentacles can indicate overwhelm, lack of balance, or difficulty managing responsibilities. It suggests the need to reassess your priorities and find a more sustainable approach to your commitments.",
  },
  {
    name: "Three of Pentacles",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Pentacles/ThreeOfPentacles.jpg",
    seed: "Pentacles",
    meaning: "The Three of Pentacles represents teamwork, collaboration, and skill development. It signifies the importance of working together towards a common goal, valuing each person's contributions, and honing your skills. It encourages you to embrace collaboration and learn from others.",
  reversedMeaning: "When reversed, the Three of Pentacles can indicate lack of teamwork, miscommunication, or feeling undervalued. It suggests the need to address conflicts and find ways to work together effectively.",
  },
  {
    name: "Four of Pentacles",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Pentacles/FourOfPentacles.jpg",
    seed: "Pentacles",
    meaning: "The Four of Pentacles symbolizes stability, security, and holding onto resources. It signifies a desire for financial security, but also the potential for being overly possessive or resistant to change. It encourages you to find a balance between saving and sharing.",
  reversedMeaning: "When reversed, the Four of Pentacles can indicate fear of loss, greed, or being overly controlling. It suggests the need to let go of material attachments and embrace a more open and generous mindset.",
  },
  {
    name: "Five of Pentacles",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Pentacles/FiveOfPentacles.jpg",
    seed: "Pentacles",
    meaning: "The Five of Pentacles represents financial hardship, loss, and feeling left out in the cold. It signifies a difficult period, but also the potential for growth and resilience. It encourages you to seek support and find strength in challenging times.",
  reversedMeaning: "When reversed, the Five of Pentacles can indicate recovery, finding support, or overcoming financial difficulties. It suggests the need to reach out for help and embrace new opportunities for growth.",
  },
  {
    name: "Six of Pentacles",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Pentacles/SixOfPentacles.jpg",
    seed: "Pentacles",
    meaning: "The Six of Pentacles symbolizes generosity, giving, and receiving. It signifies the importance of sharing resources, helping others, and finding balance in your financial dealings. It encourages you to embrace a spirit of generosity and gratitude.",
  reversedMeaning: "When reversed, the Six of Pentacles can indicate imbalance in giving and receiving, exploitation, or feeling taken advantage of. It suggests the need to reassess your boundaries and ensure that your generosity is reciprocated.",
  },
  {
    name: "Seven of Pentacles",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Pentacles/SevenOfPentacles.jpg",
    seed: "Pentacles",
    meaning: "The Seven of Pentacles represents patience, perseverance, and long-term planning. It signifies the need to evaluate your progress, reflect on your efforts, and make adjustments for future growth. It encourages you to trust the process and stay committed to your goals.",
  reversedMeaning: "When reversed, the Seven of Pentacles can indicate impatience, lack of progress, or feeling discouraged. It suggests the need to reassess your goals and find renewed motivation to continue your journey.",
  },
  {
    name: "Eight of Pentacles",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Pentacles/EightOfPentacles.jpg",
    seed: "Pentacles",
    meaning: "The Eight of Pentacles symbolizes hard work, dedication, and skill development. It signifies the importance of honing your craft, paying attention to details, and striving for excellence. It encourages you to embrace a strong work ethic and take pride in your accomplishments.",
  reversedMeaning: "When reversed, the Eight of Pentacles can indicate lack of focus, burnout, or feeling unfulfilled in your work. It suggests the need to reassess your goals and find a balance between work and personal fulfillment.",
  },
  {
    name: "Nine of Pentacles",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Pentacles/NineOfPentacles.jpg",
    seed: "Pentacles",
    meaning: "The Nine of Pentacles represents financial independence, self-sufficiency, and enjoying the fruits of your labor. It signifies a sense of accomplishment, luxury, and personal fulfillment. It encourages you to appreciate your achievements and embrace a life of abundance.",
  reversedMeaning: "When reversed, the Nine of Pentacles can indicate financial insecurity, dependence on others, or feeling unfulfilled despite material success. It suggests the need to reassess your values and find true fulfillment beyond material possessions.",
  },
  {
    name: "Ten of Pentacles",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Pentacles/TenOfPentacles.jpg",
    seed: "Pentacles",
    meaning: "The Ten of Pentacles symbolizes legacy, family, and long-term stability. It signifies the importance of building a solid foundation for future generations, valuing traditions, and creating a sense of belonging. It encourages you to nurture your relationships and create a lasting impact.",
  reversedMeaning: "When reversed, the Ten of Pentacles can indicate family conflicts, financial instability, or feeling disconnected from your roots. It suggests the need to address underlying issues and find ways to strengthen your family bonds and financial security.",
  },
  {
    name: "Page of Pentacles",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Pentacles/PageOfPentacles.jpg",
    seed: "Pentacles",
    meaning: "The Page of Pentacles represents ambition, practicality, and a desire for knowledge. It signifies a youthful spirit, eagerness to learn, and the potential for financial growth. It encourages you to embrace new opportunities and approach your goals with determination.",
  reversedMeaning: "When reversed, the Page of Pentacles can indicate lack of focus, procrastination, or feeling overwhelmed by responsibilities. It suggests the need to reassess your priorities and find a more practical approach to your goals.",
  },
  {
    name: "Knight of Pentacles",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Pentacles/KnightOfPentacles.jpg",
    seed: "Pentacles",
    meaning: "The Knight of Pentacles symbolizes reliability, hard work, and practicality. It signifies a steady and methodical approach to achieving your goals, valuing diligence and perseverance. It encourages you to stay focused and committed to your path.",
  reversedMeaning: "When reversed, the Knight of Pentacles can indicate stagnation, lack of progress, or being overly cautious. It suggests the need to find a balance between practicality and taking calculated risks to move forward.",
  },
  {
    name: "Queen of Pentacles",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Pentacles/QueenOfPentacles.jpg",
    seed: "Pentacles",
    meaning: "The Queen of Pentacles represents nurturing, practicality, and abundance. It signifies a strong connection to nature, financial stability, and the ability to create a comfortable and secure environment. It encourages you to embrace your nurturing qualities and find balance in your material and emotional life.",
  reversedMeaning: "When reversed, the Queen of Pentacles can indicate neglecting self-care, being overly focused on material possessions, or feeling overwhelmed by responsibilities. It suggests the need to prioritize your well-being and find a healthier balance in your life.",
  },
  {
    name: "King of Pentacles",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Pentacles/KingOfPentacles.jpg",
    seed: "Pentacles",
    meaning: "The King of Pentacles symbolizes financial success, stability, and leadership. It signifies a strong foundation, wise investments, and the ability to create abundance. It encourages you to embrace your leadership qualities and make practical decisions for long-term success.",
    reversedMeaning: "When reversed, the King of Pentacles can indicate financial irresponsibility, greed, or being overly focused on material wealth. It suggests the need to reassess your values and find a more balanced approach to your finances and leadership.",
  },
  {
    name: "Ace of Swords",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Swords/AceOfSwords.jpg",
    seed: "Swords",
    meaning: "The Ace of Swords represents clarity, truth, and new ideas. It signifies a breakthrough in understanding, mental clarity, and the potential for intellectual growth. It encourages you to embrace your intellect and communicate your thoughts with confidence.",
    reversedMeaning: "When reversed, the Ace of Swords can indicate confusion, miscommunication, or lack of clarity. It suggests the need to reassess your thoughts and find a clearer perspective before making decisions.",
  },
  {
    name: "Two of Swords",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Swords/TwoOfSwords.jpg",
    seed: "Swords",
    meaning: "The Two of Swords symbolizes indecision, conflict, and the need for balance. It signifies a difficult choice or a stalemate situation, urging you to find clarity and make a decision. It encourages you to trust your intuition and seek inner peace amidst uncertainty.",
    reversedMeaning: "When reversed, the Two of Swords can indicate avoidance, fear of confrontation, or being stuck in a difficult situation. It suggests the need to confront your fears and make a decision to move forward.",
  },
  {
    name: "Three of Swords",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Swords/ThreeOfSwords.jpg",
    seed: "Swords",
    meaning: "The Three of Swords represents heartbreak, grief, and emotional pain. It signifies a difficult period of loss or betrayal, urging you to acknowledge your emotions and allow yourself to heal. It encourages you to find strength in vulnerability and seek support from loved ones.",
    reversedMeaning: "When reversed, the Three of Swords can indicate healing, forgiveness, or moving on from past pain. It suggests the need to let go of emotional burdens and embrace a new chapter in your life.",
  },
  {
    name: "Four of Swords",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Swords/FourOfSwords.jpg",
    seed: "Swords",
    meaning: "The Four of Swords symbolizes rest, recovery, and introspection. It signifies a need for solitude, reflection, and rejuvenation. It encourages you to take a break, recharge your energy, and gain clarity before moving forward.",
    reversedMeaning: "When reversed, the Four of Swords can indicate restlessness, avoidance of necessary healing, or feeling overwhelmed. It suggests the need to confront your emotions and find a balance between rest and action.",
  },
  {
    name: "Five of Swords",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Swords/FiveOfSwords.jpg",
    seed: "Swords",
    meaning: "The Five of Swords represents conflict, tension, and the potential for betrayal. It signifies a situation where winning may come at a cost, urging you to consider the consequences of your actions. It encourages you to seek resolution and avoid unnecessary conflicts.",
    reversedMeaning: "When reversed, the Five of Swords can indicate resolution, compromise, or letting go of past conflicts. It suggests the need to find common ground and move forward with a sense of peace.",
  },
  {
    name: "Six of Swords",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Swords/SixOfSwords.jpg",
    seed: "Swords",
    meaning: "The Six of Swords symbolizes transition, moving on, and finding clarity. It signifies a journey towards a better situation, leaving behind difficulties, and seeking mental clarity. It encourages you to embrace change and trust in the process of healing.",
    reversedMeaning: "When reversed, the Six of Swords can indicate resistance to change, feeling stuck, or avoiding necessary transitions. It suggests the need to confront your fears and embrace the journey towards healing and clarity.",
  },
  {
    name: "Seven of Swords",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Swords/SevenOfSwords.jpg",
    seed: "Swords",
    meaning: "The Seven of Swords represents deception, strategy, and the need for caution. It signifies a situation where you may need to be strategic, avoid confrontation, or protect your interests. It encourages you to be aware of potential deceit and trust your instincts.",
    reversedMeaning: "When reversed, the Seven of Swords can indicate honesty, transparency, or the need to confront deception. It suggests the need to address underlying issues and find a more authentic approach to your situation.",
  },
  {
    name: "Eight of Swords",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Swords/EightOfSwords.jpg",
    seed: "Swords",
    meaning: "The Eight of Swords symbolizes restriction, feeling trapped, and self-imposed limitations. It signifies a situation where you may feel powerless or unable to see a way out. It encourages you to confront your fears and recognize that you have the power to change your circumstances.",
    reversedMeaning: "When reversed, the Eight of Swords can indicate liberation, breaking free from limitations, or gaining a new perspective. It suggests the need to confront your fears and take action towards your freedom.",
  },
  {
    name: "Nine of Swords",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Swords/NineOfSwords.jpg",
    seed: "Swords",
    meaning: "The Nine of Swords represents anxiety, worry, and sleepless nights. It signifies a period of mental distress, overthinking, and fear. It encourages you to confront your fears, seek support, and find healthy coping mechanisms to alleviate your worries.",
    reversedMeaning: "When reversed, the Nine of Swords can indicate finding relief from anxiety, gaining perspective, or overcoming fears. It suggests the need to confront your worries and find healthier ways to cope with stress.",
  },
  {
    name: "Ten of Swords",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Swords/TenOfSwords.jpg",
    seed: "Swords",
    meaning: "The Ten of Swords symbolizes betrayal, endings, and hitting rock bottom. It signifies a painful situation or the end of a difficult cycle. It encourages you to acknowledge your pain, learn from the experience, and embrace new beginnings.",
    reversedMeaning: "When reversed, the Ten of Swords can indicate recovery, healing, or finding a way to move on from past pain. It suggests the need to let go of the past and embrace new opportunities for growth and renewal.",
  },
  {
    name: "Page of Swords",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Swords/PageOfSwords.jpg",
    seed: "Swords",
    meaning: "The Page of Swords represents curiosity, intellect, and a thirst for knowledge. It signifies a youthful spirit, eagerness to learn, and the potential for intellectual growth. It encourages you to embrace your curiosity and communicate your ideas with clarity.",
    reversedMeaning: "When reversed, the Page of Swords can indicate immaturity, impulsiveness, or difficulty expressing thoughts. It suggests the need to develop your communication skills and find a more thoughtful approach to your ideas.",
  },
  {
    name: "Knight of Swords",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Swords/KnightOfSwords.jpg",
    seed: "Swords",
    meaning: "The Knight of Swords symbolizes action, determination, and intellectual pursuit. It signifies a strong desire to pursue your goals, take risks, and embrace challenges. It encourages you to be assertive and confident in your pursuits.", 
    reversedMeaning: "When reversed, the Knight of Swords can indicate impulsiveness, recklessness, or being overly aggressive. It suggests the need to find a balance between action and reflection, and to consider the consequences of your decisions.",
  },
  {
    name: "Queen of Swords",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Swords/QueenOfSwords.jpg",
    seed: "Swords",
    meaning: "The Queen of Swords represents intellect, clarity, and independence. It signifies a strong and analytical mind, the ability to see through illusions, and the courage to speak your truth. It encourages you to embrace your intellect and use it to navigate challenges with wisdom.",
    reversedMeaning: "When reversed, the Queen of Swords can indicate emotional detachment, harshness, or difficulty expressing emotions. It suggests the need to find a balance between intellect and emotions, and to approach situations with empathy and understanding.",
  },
  {
    name: "King of Swords",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Swords/KingOfSwords.jpg",
    seed: "Swords",
    meaning: "The King of Swords symbolizes authority, intellect, and leadership. It signifies a strong and decisive mind, the ability to make fair judgments, and the courage to stand by your principles. It encourages you to embrace your leadership qualities and use your intellect to guide others.",
    reversedMeaning: "When reversed, the King of Swords can indicate manipulation, dishonesty, or being overly critical. It suggests the need to reassess your values and find a more compassionate and ethical approach to your leadership.",
  },
  {
    name: "Ace of Wands",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Wands/AceOfWands.jpg",
    seed: "Wands",
    meaning: "The Ace of Wands represents new beginnings, inspiration, and creative energy. It signifies the potential for growth, passion, and the spark of new ideas. It encourages you to embrace your creativity and take action towards your goals.",
    reversedMeaning: "When reversed, the Ace of Wands can indicate delays, lack of motivation, or feeling uninspired. It suggests the need to reignite your passion and find new sources of inspiration to move forward.",
  },
  {
    name: "Two of Wands",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Wands/TwoOfWands.jpg",
    seed: "Wands",
    meaning: "The Two of Wands symbolizes planning, exploration, and making choices. It signifies a period of contemplation, where you may be considering new opportunities or paths. It encourages you to embrace your vision and take the necessary steps towards your goals.",
    reversedMeaning: "When reversed, the Two of Wands can indicate indecision, fear of change, or feeling stuck. It suggests the need to confront your fears and make a decision to move forward with confidence.",
  },
  {
    name: "Three of Wands",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Wands/ThreeOfWands.jpg",
    seed: "Wands",
    meaning: "The Three of Wands represents expansion, growth, and looking towards the future. It signifies a period of exploration, where you may be considering new opportunities or ventures. It encourages you to embrace your vision and take bold steps towards your goals.",
    reversedMeaning: "When reversed, the Three of Wands can indicate delays, lack of progress, or feeling stuck in your plans. It suggests the need to reassess your goals and find new ways to move forward with confidence.",
  },
  {
    name: "Four of Wands",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Wands/FourOfWands.jpg",
    seed: "Wands",
    meaning: "The Four of Wands symbolizes celebration, harmony, and community. It signifies a period of joy, where you may be celebrating achievements or milestones with loved ones. It encourages you to embrace the support of your community and find joy in shared experiences.",
    reversedMeaning: "When reversed, the Four of Wands can indicate disharmony, conflicts within relationships, or feeling disconnected from your community. It suggests the need to address underlying issues and find ways to restore harmony and connection.",
  },
  {
    name: "Five of Wands",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Wands/FiveOfWands.jpg",
    seed: "Wands",
    meaning: "The Five of Wands represents competition, conflict, and challenges. It signifies a period of struggle, where you may be facing obstacles or disagreements with others. It encourages you to embrace the challenges as opportunities for growth and find constructive ways to resolve conflicts.",
    reversedMeaning: "When reversed, the Five of Wands can indicate avoidance of conflict, lack of competition, or feeling overwhelmed by challenges. It suggests the need to confront your fears and find healthy ways to navigate conflicts and challenges.",
  },
  {
    name: "Six of Wands",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Wands/SixOfWands.jpg",
    seed: "Wands",
    meaning: "The Six of Wands symbolizes victory, recognition, and achievement. It signifies a period of success, where you may be receiving accolades or validation for your efforts. It encourages you to celebrate your accomplishments and embrace the recognition you deserve.",
    reversedMeaning: "When reversed, the Six of Wands can indicate setbacks, lack of recognition, or feeling unappreciated. It suggests the need to reassess your goals and find new ways to achieve success and recognition.",
  },
  {
    name: "Seven of Wands",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Wands/SevenOfWands.jpg",
    seed: "Wands",
    meaning: "The Seven of Wands represents perseverance, courage, and standing your ground. It signifies a period of challenges, where you may need to defend your position or beliefs. It encourages you to embrace your inner strength and stand firm in the face of adversity.",
    reversedMeaning: "When reversed, the Seven of Wands can indicate giving up, feeling overwhelmed, or avoiding confrontation. It suggests the need to confront your fears and find the courage to stand up for yourself and your beliefs.",
  },
  {
    name: "Eight of Wands",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Wands/EightOfWands.jpg",
    seed: "Wands",
    meaning: "The Eight of Wands symbolizes swift action, progress, and communication. It signifies a period of rapid movement, where things may be happening quickly or messages are being exchanged. It encourages you to embrace the momentum and take advantage of the opportunities that arise.",
    reversedMeaning: "When reversed, the Eight of Wands can indicate delays, miscommunication, or feeling stuck in a situation. It suggests the need to reassess your plans and find new ways to move forward with clarity and purpose.",
  },
  {
    name: "Nine of Wands",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Wands/NineOfWands.jpg",
    seed: "Wands",
    meaning: "The Nine of Wands represents resilience, perseverance, and the need to protect your boundaries. It signifies a period of challenges, where you may feel weary but determined to keep going. It encourages you to embrace your inner strength and stand firm in the face of adversity.",
    reversedMeaning: "When reversed, the Nine of Wands can indicate feeling overwhelmed, giving up, or being overly defensive. It suggests the need to reassess your boundaries and find a healthier approach to protecting yourself and your goals.",
  },
  {
    name: "Ten of Wands",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Wands/TenOfWands.jpg",
    seed: "Wands",
    meaning: "The Ten of Wands symbolizes burden, responsibility, and the weight of obligations. It signifies a period of feeling overwhelmed by responsibilities or carrying too much on your shoulders. It encourages you to reassess your commitments and find ways to lighten your load.",
    reversedMeaning: "When reversed, the Ten of Wands can indicate releasing burdens, finding relief, or delegating responsibilities. It suggests the need to let go of unnecessary obligations and find a more balanced approach to your commitments.",
  },
  {
    name: "Page of Wands",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Wands/PageOfWands.jpg",
    seed: "Wands",
    meaning: "The Page of Wands represents enthusiasm, creativity, and a desire for adventure. It signifies a youthful spirit, eagerness to explore new ideas, and the potential for creative growth. It encourages you to embrace your passions and take bold steps towards your goals.",
    reversedMeaning: "When reversed, the Page of Wands can indicate immaturity, lack of direction, or feeling uninspired. It suggests the need to find clarity in your passions and take a more focused approach to your creative pursuits.",
  },
  {
    name: "Knight of Wands",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Wands/KnightOfWands.jpg",
    seed: "Wands",
    meaning: "The Knight of Wands symbolizes action, adventure, and passion. It signifies a strong desire to pursue your goals, take risks, and embrace challenges. It encourages you to be assertive and confident in your pursuits, while also being mindful of the potential consequences of your actions.",
    reversedMeaning: "When reversed, the Knight of Wands can indicate impulsiveness, recklessness, or being overly aggressive. It suggests the need to find a balance between action and reflection, and to consider the consequences of your decisions.",
  },
  {
    name: "Queen of Wands",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Wands/QueenOfWands.jpg",
    seed: "Wands",
    meaning: "The Queen of Wands represents confidence, charisma, and creativity. It signifies a strong and passionate individual who embraces their inner power and inspires others. It encourages you to embrace your creativity, take charge of your passions, and lead with confidence.",
    reversedMeaning: "When reversed, the Queen of Wands can indicate insecurity, lack of confidence, or being overly controlling. It suggests the need to find a balance between assertiveness and empathy, and to embrace your true self without fear of judgment.",
  },
  {
    name: "King of Wands",
    arcana: "Minor",
    image: "/images/Tarots/MinorArcana/Wands/KingOfWands.jpg",
    seed: "Wands",
    meaning: "The King of Wands symbolizes leadership, vision, and inspiration. It signifies a strong and charismatic leader who embraces their passions and inspires others to take action. It encourages you to embrace your leadership qualities, pursue your vision with confidence, and inspire those around you.",
    reversedMeaning: "When reversed, the King of Wands can indicate arrogance, lack of direction, or being overly controlling. It suggests the need to reassess your leadership style and find a more balanced approach that inspires and empowers others.",
  },

];