import React from 'react'

const TaC = async () => {

  return (
    <main className="items-center justify-center">
      <article className="w-fit">
        <h1>TERMS AND CONDITIONS FOR SERAPHINA MOON AI TAROT READER</h1>
        <br />
        <h2 className="font-bold">EFFECTIVE DATE: 02/05/2025</h2>
        <br />
        <h2 className="font-bold">PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY BEFORE USING THE SERAPHINA MOON AI TAROT READER. </h2> 
        <h2 className="font-bold">BY ACCESSING OR USING THE SERAPHINA MOON AI TAROT READER, YOU AGREE TO BE BOUND BY THESE TERMS AND CONDITIONS.</h2>
        <br />
<p className="font-bold"> 1. DEFINITIONS</p>

1.1 "Seraphina Moon," "AI Tarot Reader," or "Service" refers to the artificial intelligence tarot reading software and related services.
<br />
1.2 "Provider," "we," "us," or "our" refers to the entity that owns, operates, and provides the Seraphina Moon AI Tarot Reader.
<br />
1.3 "User," "you," or "your" refers to any individual or entity that accesses or uses the Seraphina Moon AI Tarot Reader.
<br />
1.4 "Content" refers to any tarot readings, interpretations, responses, or other materials generated by the Seraphina Moon AI Tarot Reader.
<br />
<p className="font-bold"> 2. FICTIONAL NATURE OF SERAPHINA MOON</p>
2.1 Fictional Entity. Seraphina Moon is a fictional persona powered by artificial intelligence technology. Seraphina Moon is not a real person, does not have human capabilities, and does not possess any supernatural or psychic abilities.
<br />
2.2 No Association with Real Persons. Any resemblance to real persons, living or dead, named "Seraphina Moon" or any similar name is entirely coincidental. We expressly disclaim any association with any actual individuals bearing similar or identical names.
<br />
<p className="font-bold"> 3. ENTERTAINMENT PURPOSES ONLY</p>
3.1 Entertainment Service. The Seraphina Moon AI Tarot Reader is provided solely for entertainment and recreational purposes. All Content generated by the Service is intended for amusement only.
<br />
3.2 No Predictions. The Service does not predict future events. Any interpretations or readings provided are algorithmically generated and do not possess predictive capabilities regarding actual future events.
<br />
3.3 No Reliance. Users acknowledge and agree that the Content provided by the Service should not be relied upon for any purpose other than entertainment.
<br />
<p className="font-bold"> 4. DISCLAIMER OF PROFESSIONAL ADVICE</p>
4.1 Not Professional Advice. The Content generated by Seraphina Moon AI Tarot Reader does not constitute professional advice of any kind, including, without limitation:
<br />
a) Medical or Health Advice: The Service does not provide medical diagnoses, treatment recommendations, or health advice of any kind. Users experiencing health concerns should consult qualified healthcare professionals.
<br />
b) Legal Advice: The Service does not provide legal advice or legal services. Users with legal questions or issues should consult licensed attorneys.
<br />
c) Financial Advice: The Service does not provide financial, investment, tax, or business advice. Users seeking financial guidance should consult certified financial advisors.
<br />
d) Psychological Counseling: The Service does not provide psychological counseling, therapy, or mental health treatment. Users seeking mental health support should consult licensed mental health professionals.
<br />
4.2 No Substitute for Professional Services. Under no circumstances should the Content generated by the Service be used as a substitute for professional advice or services from qualified practitioners in relevant fields.
<br />
<p className="font-bold"> 5. LIMITATION OF LIABILITY</p>
5.1 No Liability for Decisions. The Provider and its affiliates, officers, employees, agents, partners, and licensors shall not be liable for any damages, losses, costs, or expenses arising from decisions made by Users based on Content generated by the Service.
<br />
5.2 No Liability for Content. The Provider does not guarantee the accuracy, completeness, timeliness, reliability, suitability, or availability of any Content generated by the Service.
<br />
5.3 Disclaimer of Warranties. THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT ANY WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE PROVIDER DISCLAIMS ALL WARRANTIES, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
<br />
5.4 Limitation of Damages. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE PROVIDER BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (i) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE; (ii) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE; (iii) ANY CONTENT OBTAINED FROM THE SERVICE; AND (iv) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY, WHETHER OR NOT THE PROVIDER HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE.
<br />
5.5 Cap on Liability. WITHOUT LIMITING THE FOREGOING, IN NO EVENT SHALL THE PROVIDER'S TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, OR CAUSES OF ACTION EXCEED THE AMOUNT PAID BY YOU, IF ANY, FOR ACCESSING OR USING THE SERVICE DURING THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO LIABILITY, OR ONE HUNDRED DOLLARS ($100.00), WHICHEVER IS LESS.
<br />
5.6 Essential Basis. THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN THE PROVIDER AND YOU.
<br />
<p className="font-bold"> 6. USER RESPONSIBILITIES</p>
6.1 No Reliance. You acknowledge and agree that you will not rely on the Content generated by the Service for any decisions regarding health, finances, legal matters, relationships, or any other significant life decisions.
<br />
6.2 Age Restrictions. Users must be at least 18 years of age or the age of majority in their jurisdiction, whichever is greater, to use the Service. By using the Service, you represent and warrant that you meet these age requirements.
<br />
6.3 Mental Health Considerations. Users experiencing mental health difficulties, emotional distress, or psychological issues should seek professional help rather than relying on the Service for support or guidance.
<br />
<p className="font-bold"> 7. INTELLECTUAL PROPERTY</p>
7.1 Ownership. All rights, title, and interest in and to the Service, including all intellectual property rights therein, are and will remain the exclusive property of the Provider and its licensors.
<br />
7.2 License to Use. Subject to your compliance with these Terms and Conditions, the Provider grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the Service for your personal, non-commercial entertainment purposes.
<br />
7.3 Restrictions. You shall not:
<br />
a) Copy, modify, adapt, translate, create derivative works from, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast, or otherwise exploit the Service or any portion thereof;
<br />
b) Decompile, reverse engineer, disassemble, or otherwise attempt to derive the source code of the Service;
<br />
c) Remove, alter, or obscure any copyright, trademark, or other proprietary rights notices from the Service;
<br />
d) Use the Service in any manner that could disable, overburden, damage, or impair the Service or interfere with any other party's use of the Service.
<br />
<p className="font-bold"> 8. PRIVACY</p>
8.1 Data Collection. Your use of the Service may involve the collection of certain information. For details about how we collect, use, and share your information, please refer to our Privacy Policy, which is incorporated by reference into these Terms and Conditions.
<br />
<p className="font-bold"> 9. TERMINATION</p>
9.1 Termination by Provider. The Provider reserves the right, at its sole discretion, to suspend or terminate your access to the Service at any time, with or without notice, and for any reason, including, without limitation, breach of these Terms and Conditions.
<br />
9.2 Termination by User. You may terminate your use of the Service at any time by discontinuing your use of the Service.
<br />
9.3 Effect of Termination. Upon termination, your right to use the Service will immediately cease. All provisions of these Terms and Conditions that by their nature should survive termination shall survive, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.
<br />
<p className="font-bold"> 10. GOVERNING LAW AND DISPUTE RESOLUTION</p>
10.1 Governing Law. These Terms and Conditions and your use of the Service shall be governed by and construed in accordance with the laws of Luxembourg, without giving effect to any choice or conflict of law provision or rule.
<br />
10.2 Dispute Resolution. Any dispute arising out of or relating to these Terms and Conditions or the Service shall be resolved through mediation in accordance with the Luxembourgish law.
<br />
10.3 Class Action Waiver. YOU AND THE PROVIDER AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING.
<br />
<p className="font-bold"> 11. CHANGES TO TERMS AND CONDITIONS</p>
11.1 Modifications. The Provider reserves the right, at its sole discretion, to modify or replace these Terms and Conditions at any time. If a revision is material, the Provider will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at the Provider's sole discretion.
<br />
11.2 Continued Use. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms and Conditions.
<br />
<p className="font-bold"> 12. MISCELLANEOUS</p>
12.1 Entire Agreement. These Terms and Conditions, together with any documents they expressly incorporate by reference, constitute the entire agreement between you and the Provider regarding the Service and supersede all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral.
<br />
12.2 Waiver. No waiver by the Provider of any term or condition set out in these Terms and Conditions shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of the Provider to assert a right or provision under these Terms and Conditions shall not constitute a waiver of such right or provision.
<br />
12.3 Severability. If any provision of these Terms and Conditions is held by a court or other tribunal of competent jurisdiction to be invalid, illegal, or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of the Terms and Conditions will continue in full force and effect.
<br />
12.4 Assignment. You may not assign or transfer these Terms and Conditions, by operation of law or otherwise, without the Provider's prior written consent. Any attempt by you to assign or transfer these Terms and Conditions without such consent will be null and void. The Provider may freely assign or transfer these Terms and Conditions without restriction.
<br />
12.5 Contact Information. Questions or comments about the Service or these Terms and Conditions may be directed to the Provider seraphinamooiatarot@gmail.com.
<br />
BY USING THE SERAPHINA MOON AI TAROT READER, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS AND CONDITIONS, UNDERSTAND THEM, AND AGREE TO BE BOUND BY THEIR TERMS AND CONDITIONS. IF YOU DO NOT AGREE TO THESE TERMS AND CONDITIONS, YOU MUST NOT ACCESS OR USE THE SERVICE.
      </article>
      
    </main>
  )
}

export default TaC
