import React from 'react'

const Disclaimer = async () => {

  return (
    <main className="w-2/3 items-center justify-center">
      <article className="reading-section w-fit">
        <h1>Disclaimer</h1>

        <p>
        Seraphina Moon is not a real person. She is a completely AI-generated personality, and all tarot readings produced under her name are generated by artificial intelligence. These readings are for entertainment purposes only and are not to be taken as serious advice in any area of life, especially medical, financial, psychological, legal, or personal matters.</p>
<p>
Her work is not intended as divination or spiritual counsel, and should never replace professional advice or services.
</p>
<p>
So sit back, relax, and enjoy the journey through the cards—with a sprinkle of magic, a dash of mystery, and a wink from Seraphina Moon.
</p>
<p>
Seraphina Moon is a fictional character. Any connection to a real person is purely by chance.
        </p>
      </article>
      
    </main>
  )
}

export default Disclaimer
